### ISSUE TITLE
A question about DemandPeriod class

### ISSUE THREAD

**Issue by marcolee19970823** [jdlph/Path4GMNS#16]
### My question:

In _**classes.py**_ of Path4GMNS, there are three member variables for DemandPeriod class. However, the method _**"get_file_name"**_ returns a member variable _**"file"**_, which is also inconsistent with _**settings.yml**_. Could you further explain the function and intention of this method? Many thanks!

### The code for defining DemandPeriod class in classes.py file
![image](https://user-images.githubusercontent.com/47074370/140881483-422e08c0-acf3-44cc-94f4-37ad4a10ca02.png)

### Screenshot of settings.yml file
![image](https://user-images.githubusercontent.com/47074370/140881826-91f52e83-8892-41f4-bd99-53fa3171dfcd.png)

**Comment by jdlph** [comment]
def get_file_name() had never been used and has been removed under commit fe4c0b. Thank you for point it out!
