### ISSUE TITLE
A question about agent counting

### ISSUE THREAD

**Issue by marcolee19970823** [jdlph/Path4GMNS#17]
![image](https://user-images.githubusercontent.com/47074370/141055588-5f8a2c0b-24bb-48c3-b624-f69818d51bfc.png)

In **_read_demand_** method, the OD volume is first added by 1 and then be transformed to _**integral number**_. Would this operation be excessively overestimate the real amount of OD volume? I suggest it can be first added to the obtain the true though may not be integer value and secondly be  transformed to **_integral number_**. Thank you.

**Comment by jdlph** [comment]
It really does not matter as it is only informative and is not involved in any critical computations.
