### ISSUE TITLE
Removing Links 

### ISSUE THREAD

**Issue by mazkaz** [jdlph/Path4GMNS#19]
I was wondering if there was a way of removing links without having to manually edit the csv file? My plan is to remove a link one by one and see the effect this has to the equilibrium time.

Thanks,
Marek

**Comment by jdlph** [comment]
v0.8.4 introduces the concept of special event with affected links and capacity reduction ratios. You can now disable a set of links for traffic assignment by listing them under affected_links with reduction_ratio as 0. See [In Case of Special Events](https://github.com/jdlph/Path4GMNS#in-case-of-special-events) for details.
