### ISSUE TITLE
When VDF attributes are missing, please use default alpha and beta values

### ISSUE THREAD

**Issue by asu-trans-ai-lab** [jdlph/Path4GMNS#2]
In the current version, VDF attributes are required in link.csv. They should be optional with default values used in both python and DTALite kernel versions. the capacity field in link.csv will be also used first  if VDF_cap1 does not have values.

**Comment by jdlph** [comment]
Thank you for pointing it out! It has been addressed in dev/v0.6.1 under commit cdf4614 which will be merged into the main branch. 

![image](https://user-images.githubusercontent.com/31260633/113437080-f5f78300-93b3-11eb-8eef-5f23ec558081.png)
