### ISSUE TITLE
Issue for Find Shortest Paths for All Individual Agents

### ISSUE THREAD

**Issue by YuanzhengLei** [jdlph/Path4GMNS#21]
By using this legacy way to find paths for agents and conduct traffic assignments (read_network(load_demand=True) ), we still get an exception stating, "NO VALID OD VOLUME!! DOUBLE CHECK YOUR demand.csv".
Source code: ###
network = pg.read_network(load_demand=True)
network.find_path_for_agents()

agent_id = 300
print('\norigin node id of agent is '
      f'{network.get_agent_orig_node_id(agent_id)}')
print('destination node id of agent is '
      f'{network.get_agent_dest_node_id(agent_id)}')
print('shortest path (node id) of agent, '
      f'{network.get_agent_node_path(agent_id)}')
print('shortest path (link id) of agent, '
      f'{network.get_agent_link_path(agent_id)}')

agent_id = 1000
print('\norigin node id of agent is '
      f'{network.get_agent_orig_node_id(agent_id)}')
print('destination node id of agent is '
      f'{network.get_agent_dest_node_id(agent_id)}')
print('shortest path (node id) of agent, '
      f'{network.get_agent_node_path(agent_id)}')
print('shortest path (link id) of agent, '
      [f'{network.get_agent_link_path(agent_id)}')]([demand.csv](https://github.com/jdlph/Path4GMNS/files/9688167/demand.csv))
pg.output_agent_paths(network)
###
Errer:###
Please provide settings.yml next time!
Engine will set up one demand period and one agent type using default values for you, which might NOT reflect your case!

read node.csv
the number of nodes is 357
read link.csv
the number of links is 646
read demand.csv
the number of agents is 0
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
[<ipython-input-15-e9b68bc81fc7>](https://localhost:8080/#) in <module>
----> 1 network = pg.read_network(load_demand=True)
      2 network.find_path_for_agents()
      3 
      4 agent_id = 300
      5 print('\norigin node id of agent is '

1 frames
[/usr/local/lib/python3.7/dist-packages/path4gmns/utils.py](https://localhost:8080/#) in read_demand(input_dir, file, agent_type_id, demand_period_id, zones, column_pool, check_connectivity)
    576 
    577         if total_agents == 0:
--> 578             raise Exception('NO VALID OD VOLUME!! DOUBLE CHECK YOUR demand.csv')
    579 
    580 

Exception: NO VALID OD VOLUME!! DOUBLE CHECK YOUR demand.csv
[###[](url)](url)

**Comment by YuanzhengLei** [comment]
[demand.csv](https://github.com/jdlph/Path4GMNS/files/9688171/demand.csv)

**Comment by jdlph** [comment]
We thank you for opening an issue! Please leave a reason when you close it. Otherwise, it will leave the developers with no clue.

Please consider using screenshots or [code snippets in Markdown](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for better readability. 

Regarding the issue itself, read_network(load_demand=True) will automatically check OD connectivity which **requires zone info to be specified in node.csv**. Otherwise, you will get the exception you just reported.
