### ISSUE TITLE
Units of some parameters are unclear

### ISSUE THREAD

**Issue by Anjun93** [jdlph/Path4GMNS#24]
Here are some parameters whose units are unclear:
(1) accessibility in time or distance
(2) distance in km or mile or meter
(3) free_speed in mph or km/h
Hope to indicate the units in the output file or the documentation file.

**Comment by jdlph** [comment]
Thank you for opening up this ticket!

As stated in the [tutorial](https://github.com/jdlph/Path4GMNS/blob/dev/tests/tutorial.ipynb), Path4GMNS uses **mile** and **mile per hour (mph)** as the default units for length and speed in its internal calculation. 

In od_accessibility.csv, the accessibility between each OD pair is defined as the corresponding free flow travel time, which is in **minute**. We shall enclose this information in the docstring along with the next release.
