### ISSUE TITLE
A typo found in accessibility.py

### ISSUE THREAD

**Issue by chongnanli1997** [jdlph/Path4GMNS#3]
![image](https://user-images.githubusercontent.com/54906999/116000046-39df5000-a621-11eb-81d0-8a8f6ba68b4c.png)

Hello, you missed a letter 'i' within the word "accessibility". Thank you.

**Comment by jdlph** [comment]
It has been fixed along with some others under commit 5f880c7 in the dev branch, which will be merged with the master soon. Thank you for pointing it out!!
