### ISSUE TITLE
Is UE in DTA necessary ?

### ISSUE THREAD

**Issue by wangyinpu** [jdlph/Path4GMNS#30]
When i use pg.perform_network_assignment_DTALite(mode=2, column_gen_num, column_update_num)，the mode is UE + DTA, the UE process is necessary before DTA.
If I have my own agent.csv, can I just call the DNL in PATH4GMNS?
Thank you!

**Comment by jdlph** [comment]
UE is the prerequisite to conduct DTA for both Path4GMNS and DTALite. 

pg.perform_network_assignment_DTALite(mode=2, column_gen_num, column_update_num) is actually calling DTALite embedded in Path4GMNS. DTALite only supports an integrated run of UE + DTA. In other words, you cannot bypass the UE process and directly run DTA using your own agent.csv.

However, this specific running mode is supported by the simulation module in Path4GMNS. You can directly call pg.perform_simple_simulation(network) to perform DTA based on your own agent.csv. The full sample code is listed below.

```python
import path4gmns as pg

network = pg.read_network()
pg.read_zones(network)
pg.load_demand(network)

pg.perform_simple_simulation(network)
print('complete dynamic simulation.\n')

print('writing agent trajectories')
pg.output_agent_trajectory(network)
```

You can even continue the UE process starting from your own agent.csv. Details can be found [here](https://path4gmns.readthedocs.io/en/latest/usecases.html#perform-path-based-ue-traffic-assignment-using-the-python-column-generation-module).

As this "issue" is more toward a question or a discussion, in the future you may want to consider [discussions](https://github.com/jdlph/Path4GMNS/discussions), which is a more proper place.

**Comment by wangyinpu** [comment]
您好，您的邮件我已收到，谢谢。Hello, your email has been received, thank you.
