### ISSUE TITLE
KeyError: (0,0,0) in setup_spnetwork()

### ISSUE THREAD

**Issue by Gyrolyn** [jdlph/Path4GMNS#36]
hello guys and thank you for making this code this is a problem i'm having for a project i'm importing a small network from pyrosm and trying to use UE on it but it gives keyerror: (0,0,0) to me 
[issue report.zip](https://github.com/jdlph/Path4GMNS/files/12014830/issue.report.zip)

**Comment by jdlph** [comment]
Thank you for reporting this issue! Please include a screenshot of the error from your terminal along with the version of Path4GMNS for this particular run.

**Comment by Gyrolyn** [comment]
i'm using jupyter notebook but i have added a screenshot of output error in zip file

**Comment by jdlph** [comment]
The current implementation of setup_spnetwork() in class Assignment requires the zone id's to be consecutive integers.  This is one of the [known issues](https://github.com/users/jdlph/projects/1). For the time being, you may want to change the zone ids in node.csv and demand.csv according to the aforementioned requirement.

I will leave this issue open until a permanent fix is developed.

**Comment by jdlph** [comment]
The issue has been fixed under [8b9aff4](https://github.com/jdlph/Path4GMNS/commit/8b9aff418a4f82d3efba0bf8e619563b09d78ed5). This fix simply drops the consecutive requirement but still needs the zone id's to be integers. It will be included in the next release (i.e., v0.9.4). 

I attached the screenshot of a smooth run by executing your script after this fix for your reference. Thank you again for reporting this issue!

<img width="471" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/31260633/4947b3ae-e493-4f1e-b5fc-6fec9f9383ee">

**Comment by jdlph** [comment]
[v0.9.5](https://github.com/jdlph/Path4GMNS/releases/tag/v0.9.5) further drops the previous requirement that the zone id's to be integers. Now zone id's can be any arbitrary values. Detailed update can be found under [cce76e6](https://github.com/jdlph/Path4GMNS/commit/cce76e6552b44f2e0bbccf0b8b5cb67f66f06a6f).
