### ISSUE TITLE
the output result doesn't seem change for different demand files

### ISSUE THREAD

**Issue by Gyrolyn** [jdlph/Path4GMNS#39]
hey guys thanks for later fixes but i still have some problems with demand.csv and the result not making sense even after reading your guidance in discord server i try to showcase my work  as best as i can and thanks for putting the time and maintaining your code.
so i made node.csv and link.csv as the files attached below and made the demand.csv through a python code to make it random everytime it runs the code then put it in a loop to run for 12 times then merged the result into one spreadsheet but the result didn't seem to change even when demand volume and ODs were completely different can i have your opinion on it if i'm doing anything wrong with your code like loading the demand file or is it something wrong with the code i even tried different types of loading the demand.csv file with samples that have been in your library but none seemed to work and gave the "NO VALID OD VOLUME!! DOUBLE CHECK YOUR demand.csv" error (the said error didn't happen in my own main code just for trying to use legacy mode or other ways to load the demand.csv file)
[code.zip](https://github.com/jdlph/Path4GMNS/files/12444837/code.zip)
link below has the the jupyter notebook code as well
https://github.com/Gyrolyn/vulnerability_management2

**Comment by Gyrolyn** [comment]
the merged result is in result2 directory under the merged.xlsx file sheet3 you can see that the minimum/maximum and average numbers haven't changed in each iteration

**Comment by jdlph** [comment]
Thank you for opening up an issue! Please provide the following information for us to investigate.

1. A brief summary on what your issue is.
2. Which functionality of Path4GMNS did you use for your runs?
3. Your source code as an attachment.

**Comment by jdlph** [comment]
> 

Please provide a figurative illustration.

**Comment by jdlph** [comment]
> the merged result is in result2 directory under the merged.xlsx file sheet3 you can see that the minimum/maximum and average numbers haven't changed in each iteration

Please provide a figurative illustration.

**Comment by Gyrolyn** [comment]
my goal is to load a road network and give it a traffic assignment then analyse the result based on their vulnerability parameters after removing a certain road from network i did this in a loop and with different random traffic assignments to see the result on how much the parameters change with different traffic assignments
1. The problem is even when i change the demands drastically both in case of the destination and origin and volume of demands between my nodes the result doesn't change ---> result being my vulnerability parameters 
2. I believe my problem is with reading the demand file witch happens fine the first time and it doesn't load the second time it runs in a loop perhaps
3. here is the source code 
[Dar es salam.zip](https://github.com/jdlph/Path4GMNS/files/12499483/Dar.es.salam.zip)

**Comment by jdlph** [comment]
We have **ZERO knowledge** on your project and how you use Path4GMNS. We can only look into issues directly related to the functionality of Path4GMNS itself. Please consider providing the following information to facilitate the investigation. 

1. How do you define your vulnerability parameters? How are they related to demand and the traffic assignment result?
2. Attach a simplified source and data set to demonstrate the issue. In other words, prepare two different demand files and a simple script of your core code to show the identical result after loading the different demands.

**Comment by Gyrolyn** [comment]
hey guys i'm sorry to have taken your time i've found the solution for that the problem was this: everytime i needed to have a network and run different types of demand on the same network and then gather the result. so i made a network and path4gmns was reading the road and demand files for the first time but it couldn't replace newely made demand file into the currently using network and kept giving the same result with little differences so i made a new network everytime i wanted to change the demend file and it worked fine. or at least i think that was the problem it is fixed now for me.
thanks for giving attention to updating and answering issues.
