### ISSUE TITLE
tutorial.ipynb will not run

### ISSUE THREAD

**Issue by rkn2** [jdlph/Path4GMNS#41]
I am using the current tutorial.ipynb however when I get to step 3.2 Synthesize Zones and OD Demand Matrix, I get an error back. I have not changed any code or the datafiles it is using--I am just trying to run the original notebook to learn more about the code in general. Thanks for your help!
<img width="953" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/51692cb6-a7d1-40bf-a2a8-934a5d715e87">

**Comment by rkn2** [comment]
Additionally I tried to get around this using my own data from grid2demand (attached here) and I got a different error when I tried to run section 3.1 basic functionalities. 
<img width="624" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/a145f5ef-4a73-4148-91b6-4ff02cb535de">
...continued...
<img width="948" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/c94f6cea-b372-4591-b8bc-999f1271fc96">

Files if it is helpful: 
[link.csv](https://github.com/jdlph/Path4GMNS/files/12579390/link.csv)
[node.csv](https://github.com/jdlph/Path4GMNS/files/12579391/node.csv)
[input_agent.csv](https://github.com/jdlph/Path4GMNS/files/12579385/input_agent.csv)
[zone.csv](https://github.com/jdlph/Path4GMNS/files/12579386/zone.csv)
[poi_trip_rate.csv](https://github.com/jdlph/Path4GMNS/files/12579387/poi_trip_rate.csv)
[accessibility.csv](https://github.com/jdlph/Path4GMNS/files/12579388/accessibility.csv)
[demand.csv](https://github.com/jdlph/Path4GMNS/files/12579389/demand.csv)

**Comment by jdlph** [comment]
The first issue is related to the setup of synthesized zone id's in _synthesize_grid(), where zone id shall be string. It has been fixed under commit 403be24.

**Comment by jdlph** [comment]
The second issue comes from the data itself. This is data type inconsistency between node.csv and link.csv in terms of node id. Specifically, node id's are all decimal numbers in node.csv but integers in link.csv. For example, the id's of the two nodes are 0.0 and 1.0. 

<img width="850" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/31260633/cf8b1efd-194d-4c49-8679-300900069481">

Later on, when you load link.csv and hit the first link (from_node_id: 0 and to_node_id: 1), Path4GMNS will throw an exception to indicate this link is invalid as those nodes are not present in node.csv. 

This issue can be avoided if you use any version prior to v0.9.5 (e.g., install v0.9.4 through the following command), where node id is required to be integer. v0.9.5 drops this requirement by allowing any arbitrary value. See [here](https://github.com/jdlph/Path4GMNS/releases/tag/v0.9.5) for details.

```bash
$ pip install path4gmns==0.9.4
```

An alternative way is to manually covert node id to integer in node.csv. The following is the screenshot of a smooth run after the conversion.

<img width="1250" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/31260633/859f4077-aea7-4a2f-b686-2ba466af1ab1">

This thread will be closed as the underlying data inconsistency come from an application upstream to Path4GMNS, which could be either osm2gmns or grid2demand. If you have any follow-up questions, you can reopen it. Thank you again for reporting this issue!

**Comment by rkn2** [comment]
> The first issue is related to the setup of synthesized zone id's in _synthesize_grid(), where zone id shall be string. It has been fixed under commit [403be24](https://github.com/jdlph/Path4GMNS/commit/403be24c9b90207ac7320aac598d7b1975633f6c). It will be part of v0.9.7 in the next release.

Hi so is this accessible now? Or do I have to wait for some time? After your restponse I tried to force the install of the latest version but it doesn't seem to be able to connect to 0.9.7. 
<img width="304" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/51bb441a-5251-41ae-868e-34a887cd4087">
and then it again breaks at 3.2 
<img width="878" alt="image" src="https://github.com/jdlph/Path4GMNS/assets/22533171/b8f08cd6-c143-491d-9ee4-ee4d93b13776">

**Comment by jdlph** [comment]
v0.9.7 is not released yet. You would have to wait until it is published on PyPI or build the package on your own using the latest code from the [dev branch](https://github.com/jdlph/Path4GMNS/tree/dev). Please see [**2. Build and Install the Python Package**](https://path4gmns.readthedocs.io/en/latest/installation.html#build-path4gmns-from-source) for instructions.
