### ISSUE TITLE
we need to update the tutorial to remove the outdated functions such as read_zones(network)

### ISSUE THREAD

**Issue by asu-trans-ai-lab** [jdlph/Path4GMNS#48]
I believe that ve we do not need zone.csv so the function is not needed. We read zone_id only from field zone_id in file node.csv 
pg.read_zones(network)

https://github.com/jdlph/Path4GMNS/blob/dev/tutorial/tutorial.ipynb

**Comment by jdlph** [comment]
It has been fully addressed in v0.9.9. The new release removes read_zones() and introduces a new public API read_demand() to unify demand and zone synthesis, and demand (and synthetic zone) loading. Details and examples can be found in [Tutorial](https://github.com/jdlph/Path4GMNS/blob/master/tutorial/tutorial.ipynb) and [Use Cases](https://path4gmns.readthedocs.io/en/stable/usecases.html).
