### ISSUE TITLE
Lost file bug?

### ISSUE THREAD

**Issue by Milleupup** [jdlph/Path4GMNS#50]
pg.find_ue(network, column_gen_num, column_update_num)

ERROR:

AttributeError: module 'path4gmns' has no attribute 'read_demand'
![image](https://github.com/user-attachments/assets/ea2f0453-a254-47c5-a6d6-698faf90c2a8)

**Comment by jdlph** [comment]
It looks like you encountered this error when you were working on [Tutorial](https://github.com/jdlph/Path4GMNS/blob/master/tutorial/tutorial.ipynb). It arises as you were calling a newer API (which is only available from v0.9.9) from an older version (v0.9.8 or early). 

You can try it again with [v0.9.9](https://pypi.org/project/path4gmns/0.9.9/) which was just [released](https://github.com/jdlph/Path4GMNS/releases/tag/v0.9.9). The error shall vanish.

I will mark it as closed. If the error persists, you can reopen this thread.

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by Milleupup** [comment]
> It looks like you encountered this error when you were working on [Tutorial](https://github.com/jdlph/Path4GMNS/blob/master/tutorial/tutorial.ipynb). It arises as you were trying to call a newer API introduced in v0.9.9 (which was not released back then) from an older version (v0.9.8 or early).
> 
> The error shall vanish with the newly released [v0.9.9](https://pypi.org/project/path4gmns/0.9.9/). Details regarding its major changes can be found [here](https://github.com/jdlph/Path4GMNS/releases/tag/v0.9.9).
> 
> I will mark it as closed. If the error persists, you can reopen this thread.

yep! i'm working on [Tutorial] ,
However,after i upgrade the package,this time find_ue return errors!!!
![image](https://github.com/user-attachments/assets/aa60ecd3-22a8-471b-8d6b-5eaf8fad6577)
