### ISSUE TITLE
A suggestion about assertion statement

### ISSUE THREAD

**Issue by marcolee19970823** [jdlph/Path4GMNS#7]
Hi, I was learning **Path4GMNS/path4gmns/colgen.py/def perform_column_generation**.
I saw you used the assertion statement like this.
![image](https://user-images.githubusercontent.com/47074370/122327136-fab5e700-cf5f-11eb-891e-cf4e1f7015e4.png)

The full version of the assertion statement is shown as follows:
![image](https://user-images.githubusercontent.com/47074370/122327121-f7226000-cf5f-11eb-815c-bf5ca275321a.png)

Actually, you can add the optional message to let users know what’s happening if they meet an **AssertionError**. Just take the path4gmns code from the screenshot as an example:
![123](https://user-images.githubusercontent.com/47074370/122327236-233de100-cf60-11eb-9b04-ef528f50ac0f.png)

Thank you.

**Comment by jdlph** [comment]
The optional messages may not be needed here as the two assertions are quite straightforward. If a user accidently provided negative numbers to them, the error message from the Python interpreter (as below) is intuitive and sustained. 

File "~\Anaconda3\lib\site-packages\path4gmns\colgen.py", line 352, in perform_column_generation
    assert(iter_num>=0)
AssertionError

Your suggestion is still appreciated!!
