### ISSUE TITLE
A typo in colgen.py

### ISSUE THREAD

**Issue by marcolee19970823** [jdlph/Path4GMNS#8]
Hi, there is a typo. It should be "column_update_num" as shown in the red rectangle. Thank you.
![image](https://user-images.githubusercontent.com/47074370/122352205-7a07e280-cf81-11eb-9e16-7f29dd2f2441.png)

**Comment by jdlph** [comment]
They have been fixed in commit 9c4e1b6. Thank you for pointing them out!
